<?php

$itemList = $this->getFaqCollection();

?>
<div>
  <h1>Faq list</h1>
  <div>
    <?php if($itemList->count() > 0):?>
        <ul>
          <?php foreach ($itemList as $item):?>
            <li>
              <div>
                <h3><?php echo $item->getQuetion()?></h3>
                <div><?php echo $item->getAnswer()?></div>
              </div>
            </li>
          <?php endforeach;?>
        </ul>
    <?php else:?>
        <div class="error"><?php echo  Mage::helper('mike_faq')->__('Faq list is empty!')?></div>
    <?php endif?>
  </div>
</div>
